package com.coditas.unusedImportsBot;/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import com.thoughtworks.qdox.JavaProjectBuilder;
import com.thoughtworks.qdox.model.JavaSource;

import javax.swing.*;
import java.io.*;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.*;

import static com.coditas.unusedImportsBot.Bot.*;

/**
 * @author Coditas
 */
public class BotV3 extends javax.swing.JFrame {
    static List<String> listFiles = new ArrayList<>();

    /**
     * Creates new form swinggui
     */
    public BotV3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("CLICK FOR UNUSED IMPORTS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("CLICK FOR IF ELSE SCANNER");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("CLICK FOR UNWANTED STRING");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton4.setText("CHOOSE FOLDER FOR SCANNING");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    jButton4ActionPerformed(evt);
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        });

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(235, 235, 235)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jScrollPane2)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jButton1)
                                                                .addGap(117, 117, 117)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jButton4)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(81, 81, 81)
                                                                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(137, 137, 137)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1054, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(187, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton2)
                                        .addComponent(jButton3)
                                        .addComponent(jButton1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 678, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        UnusedImports();
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        IfElse();

    }

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
        UnwantedString();
    }

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) throws IOException {
        fileChooser();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BotV3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BotV3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BotV3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BotV3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BotV3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private static javax.swing.JTextArea jTextArea1;
    private static javax.swing.JTextArea jTextArea2;

    // End of variables declaration
    public static void UnusedImports() {
        try {
            List<String> detailsImport = new ArrayList<>();
            detailsImport.add("UNUSED IMPORTS \n");
            for (String filesContent : listFiles) {
                JavaProjectBuilder builder = new JavaProjectBuilder();
                builder.addSource(new File(filesContent));
                detailsImport.add("File path: " + filesContent + "\n");
                Collection<JavaSource> sources = builder.getSources();
                String print;
                for (JavaSource sourceString : sources) {
                    print = printUnusedImports(String.valueOf(sourceString));
                    if(!print.isEmpty()) {
                        detailsImport.add("Unused imports are: " + "\n" + print + "\n");
                    }
                    else{
                        detailsImport.add("Unused imports are: "+null+"\n");
                    }
                }
                Reader inputString = new StringReader(String.valueOf(detailsImport));
                jTextArea1.read(inputString, "READING FILE :-)");

            }
        } catch (Exception e) {
            e.printStackTrace();
        }


    }

    public static void UnwantedString() {

        try {
            List<String> detailsString = new ArrayList<>();
            detailsString.add("UNWANTED STRING \n");
            for (String filesContent : listFiles) {
                JavaProjectBuilder builder = new JavaProjectBuilder();
                builder.addSource(new File(filesContent));
                Collection<JavaSource> sources = builder.getSources();
                List<String> list = List.of(String.valueOf(sources).split("\""));
                Set<String> uniqueWords = new HashSet<>(list);
                for (String word : uniqueWords) {
                    if (Collections.frequency(list, word) > 1 && !word.isEmpty()) {
                        if (!word.startsWith(")"))
                            detailsString.add("File path: " + filesContent + "\n");
                        detailsString.add("word that is repeated: \"" + word + "\" : " + "number of times repeated: " + Collections.frequency(list, word) + "\n");
                        detailsString.add("Trying adding Constants \n");

                    } else
                        detailsString.add("Congrats No Unwanted String");
                }

                Reader inputString = new StringReader(String.valueOf(detailsString));
                jTextArea1.read(inputString, "READING FILE :-)");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }


    public static void IfElse() {
        try {
            List<String> detailsString = new ArrayList<>();
            List<String> detailsImport = new ArrayList<>();
            detailsImport.add("UNUSED IMPORTS \n");
            for (String filesContent : listFiles) {
                JavaProjectBuilder builder = new JavaProjectBuilder();
                builder.addSource(new File(filesContent));
                File file = new File(filesContent);
                String[] ifStatement = null;
                FileReader fr = new FileReader(file);
                BufferedReader br = new BufferedReader(fr);
                String str;
                // Word to search
                String search = "if";
                String search2 = "else";
                // Initializes the counter of word to zero
                int count = 0;
                // Read the contents of the file
                while ((str = br.readLine()) != null) {
                    // Split the word using space
                    ifStatement = str.split(" ");
                    for (String word : ifStatement) {
                        //Searching for the word
                        if ((word.equals(search) && word.equals(search2)) || (word.equals(search))) {
                            // If present, increment the counter
                            count++;
                        }
                    }
                }
                if (count != 0) {
                    detailsString.add("File path: " + filesContent + "\n");
                    detailsString.add("The if statement is present \"" + count + "\" : " + "times in the file" + "\n");
                    detailsString.add("Use  switch case instead\n");
                    detailsImport.add("\n");
                } else {
                    detailsString.add("File path: " + filesContent+"\n");
                    detailsString.add("The if statement doesn't exist in the file!\n");
                    detailsString.add("\n");
                }
                fr.close();
            }
            Reader inputString = new StringReader(String.valueOf(detailsString));
            jTextArea1.read(inputString, "READING FILE :-)");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }


    public static void fileChooser() throws IOException {
        JFileChooser fc = new JFileChooser();
        fc.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        int returnVal = fc.showOpenDialog(frame);
        List<String> filepath = new ArrayList<>();
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            try {
                listFiles = findFiles(Paths.get(fc.getSelectedFile().getAbsolutePath()), "java");
                filepath.add(fc.getSelectedFile().getAbsolutePath());
                Reader inputString = new StringReader(String.valueOf(filepath));
                jTextArea2.read(inputString, "READING FILE :-)");
            } catch (IOException e) {
                e.printStackTrace();
            }
        } else {
            filepath.add(null);
            Reader inputString = new StringReader(String.valueOf(filepath));
            jTextArea2.read(inputString, "READING FILE :-)");
            System.out.println("Operation is CANCELLED :(");
        }
    }
}
